repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md"]
      - id: detect-private-key
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.10.0
    hooks:
      - id: shellcheck
        name: shellcheck
        args: ["--rcfile=.shellcheckrc"]
        files: ^scripts/.*\.sh$
  - repo: https://github.com/bridgecrewio/checkov
    rev: 3.2.451
    hooks:
      - id: checkov
        name: checkov
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.8.3
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: v1.11.0
    hooks:
      - id: zizmor
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint
        name: actionlint
        description: Lint GitHub Actions workflow files
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.33.2
    hooks:
      - id: check-github-workflows
      - id: check-dependabot
      # - id: check-github-actions
  # - repo: local
  #   hooks:
  #     - id: terraform-docs
  #       name: Terraform Docs Generator
  #       description: Generate Terraform documentation using terraform-docs
  #       entry: scripts/hooks/terraform-docs.sh
  #       language: system
  #       types: [terraform]
  #       stages: [pre-commit]
  #       files: '^terraform/modules/'
