# Site configuration
site_url: https://thatmlopsguy.github.io/dokaseca-control-plane
site_author: That MLOps Guy
site_name: Doka Seca
site_description: A comprehensive framework for bootstrapping cloud-native platforms using Kubernetes in Docker (Kind)

# Repository
repo_url: https://github.com/thatmlopsguy/dokaseca-control-plane
repo_name: dokaseca-control-plane

# Navigation
nav:
  - Overview: index.md
  - Getting Started:
    - Installation: getting_started/install.md
    - Architecture: getting_started/architecture.md
    - Repo Structure: getting_started/repo_structure.md
    - Teams and Roles: getting_started/teams.md
  - Identity: identity.md
  - Catalog: catalog.md
  - Repository: repository.md
  - Portal: portal.md
  - GitOps: gitops.md
  - Networking: networking.md
  - Observability: observability.md
  - Compliance: compliance.md
  - Security: security.md
  - Data Streams: streams.md
  - Data Storage: storage.md
  - Machine Learning: machine_learning.md
  - Cost Management: cost.md
  - Chaos Engineering: chaos_engineering.md
  - Disaster Recovery: backup.md
  - Multi cluster: multicluster.md
  - Resources:
    - Glossary: glossary.md
    - Contributing: contributing.md
    - Documentation: documentation.md
    - Release Notes: releases.md
    - Roadmap: roadmap.md
    - References: references.md
  - Architecture Decisions:
    - Overview: adr/index.md
    - 0001 - Use ADRs: adr/001-use-architecture-decision-records.md
    - 0002 - External Secrets Multi-Tenancy: adr/002-external-secrets-operator-multi-tenancy.md
    - 0003 - GitOps with ArgoCD: adr/003-argocd-hub-and-spoke-configuration.md
    - 0004 - Preview Environments: adr/004-preview-env-argocd-vcluster.md

# Configuration
theme:
  name: "material"
  locale: en
  font: false
  favicon: assets/logos/favicon.svg
  logo: assets/logos/logo.svg
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: amber
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: amber
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
  features:
    - navigation.footer

# Plugins
plugins:
  - search
  - git-revision-date-localized:
      type: timeago
      fallback_to_build_date: true
  - git-authors
  # TODO: Enable these plugins when ready
  # This plugin is used to generate the ADR index page
  # mkdocs-material-adr/adr
  # mkdocs-asciinema-player

# Markdown Extensions
markdown_extensions:
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets:
      check_paths: true
  - admonition

# Copyright
copyright: Copyright &copy; 2025 That MLOps Guy

# Extra configuration
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/thatmlopsguy/dokaseca-control-plane
    - icon: fontawesome/solid/globe
      link: https://thatmlopsguy.github.io/

# Custom CSS
# extra_css:
#   - "assets/css/custom.css"

# # Custom JS
# extra_javascript:
#   - "assets/js/custom.js"
